@baseUrl = https://backend-053-729492539702.us-central1.run.app/api/v1/notes

### 1. Ambil Semua Catatan (GET)
GET {{baseUrl}}
Accept: application/json

###

### 2. Tambah Catatan Baru (POST)
POST {{baseUrl}}
Content-Type: application/json

{
    "judul": "Tes dari Cloud Run",
    "isi": "Catatan ini dikirim langsung ke database melalui backend yang sudah di-deploy."
}

###

### 3. Edit Catatan (PUT)
PUT {{baseUrl}}/1
Content-Type: application/json

{
    "judul": "Update via API.REST",
    "isi": "Konten berhasil diperbarui di server Cloud Run."
}

###

### 4. Hapus Catatan (DELETE)
DELETE {{baseUrl}}/1